---
- name: Configure K3s Insecure Registry
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Ensure /etc/rancher/k3s directory exists
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Create registries.yaml
      copy:
        dest: /etc/rancher/k3s/registries.yaml
        content: |
          mirrors:
            "10.203.247.224:5050":
              endpoint:
                - "http://10.203.247.224:5050"
            "k8s-registry.local:5050":
              endpoint:
                - "http://10.203.247.224:5050"
        mode: '0644'

    - name: Restart k3s status
      service:
        name: k3s
        state: restarted
      when: "'server' in group_names"
    
    - name: Restart k3s-agent status
      service:
        name: k3s-agent
        state: restarted
      when: "'agent' in group_names"
